### ISSUE TITLE
UnicodeEncodeError on order notification due to euro sign

### ISSUE THREAD

**Issue by jaywink** [shoopio/shoop#362]
Shoop 3.0, testing out the notification system. Created a trigger to send an email when order is created.

Error seems to be caused by `€`, which is coming from the core `{{ order }}` template tag.

    [pid: 1238|app: 0|req: 22/28] xx.xx.xx.xx () {64 vars in 1414 bytes} [Sat Feb 27 21:51:10 2016] GET /order/payment/5/l60LmHObvlY6dzfjpwuIKUbMRP6eW7CQ/ => generated 0 bytes in 54 msecs (HTTP/1.1 302) 5 headers in 233 bytes (1 switches on core 1)
    [2016-02-27 21:51:10,216] (shoop.simple_order_notification:ERROR): Failed to send order notification to ['*****@*****.***']
    Traceback (most recent call last):
      File "/app/path/venv/lib/python3.4/site-packages/shoop/front/apps/simple_order_notification/__init__.py", line 49, in send_simple_order_notification
        message.send()
      File "/app/path/venv/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
        return self.get_connection(fail_silently).send_messages([self])
      File "/app/path/venv/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 36, in send_messages
        self.write_message(message)
      File "/app/path/venv/lib/python3.4/site-packages/django/core/mail/backends/console.py", line 23, in write_message
        self.stream.write('%s\n' % msg_data)
    UnicodeEncodeError: 'ascii' codec can't encode character '\u20ac' in position 461: ordinal not in range(128)
    [pid: 1238|app: 0|req: 23/29] xx.xx.xx.xx () {64 vars in 1417 bytes} [Sat Feb 27 21:51:10 2016] GET /order/complete/5/l60LmHObvlY6dzfjpwuIKUbMRP6eW7CQ/ => generated 13981 bytes in 226 msecs (HTTP/1.1 200) 5 headers in 263 bytes (1 switches on core 0)

Template looks like this:

![selection_225](https://cloud.githubusercontent.com/assets/1174866/13375038/112c735a-dd9e-11e5-9ca9-301b1f4c3b1e.png)

**Comment by jaywink** [comment]
Hmm sorry, false alarm. Seems I still had console email backend on, and for some reason this was failing to print there on my server (local dev works fine). Switched to SMTP backend and things work fine.

Also, noticed this isn't even the notification scripts system but the `simple_order_notification` app :dancer:
